require("arima.plugins-setup")
require("arima.core.options")
require("arima.core.keymaps")
require("arima.core.colorscheme")

require("arima.plugins.comment")
require("arima.plugins.nvim-tree")
require("arima.plugins.lualine")
require("arima.plugins.telescope")
require("arima.plugins.nvim-cmp")
require("arima.plugins.lsp.mason")
require("arima.plugins.lsp.lspsaga")
require("arima.plugins.lsp.lspconfig")
require("arima.plugins.lsp.null-ls")
require("arima.plugins.autopairs")
require("arima.plugins.treesitter")
require("arima.plugins.gitsigns")
